# -*- coding: utf-8 -*-
"""lstm app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TF4NPBlDjAoPqOVI2lZ3aMxU5qvxbkS5
"""

pip install streamlit

import streamlit as st
from tensorflow.keras.models import load_model
import numpy as np

# Load model
model = load_model('final_new_lstm_model.h5')

# Fungsi untuk ekstraksi fitur URL
def extract_features_and_vectors(url):
    # (Tambahkan logika ekstraksi fitur dan vektor Word2Vec)
    # Misal: return np.array([...])
    pass

# Aplikasi Streamlit
st.title("Phishing URL Detection")
user_input = st.text_input("Enter URL for detection:")

if st.button("Predict"):
    if user_input:
        features = extract_features_and_vectors(user_input)
        features = features.reshape((1, 1, -1))
        prediction = model.predict(features)
        result = "Non-Phishing" if prediction[0] > 0.5 else "Phishing"
        st.write(f"The URL is classified as: **{result}**")
    else:
        st.write("Please enter a valid URL.")

